### ISSUE TITLE
Wrong version of protobuf included by default (3.1.0 instead of 3.0.2)

### ISSUE THREAD

**Issue by kaligrafy** [ka7eh/rust-geobuf#8]
protobuf version 3.1.0 installs by default with this crate, but it is incompatible and I get this error when bulding: 
cannot find value `VERSION_3_0_2` in crate `protobuf`

I don't know why the 3.1 version is automatically installed, even if I forced it with protobuf = '3.0.2'

**Comment by kaligrafy** [comment]
I use rust 1.62.1

**Comment by ka7eh** [comment]
The issue was that `protobuf = "3.0"` was being interpreted as `>=3.0, < 4`.
I fixed it  (https://github.com/ka7eh/rust-geobuf/commit/cbbcf00502af930605f1ced4aceb3adca2b57c79) and now Cargo uses an exact version of protobuf.

**Comment by kaligrafy** [comment]
Nice! Thanks for the fast fix!
